name: maida_test
description: "Maida Test App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  connectivity_plus: ^6.1.3
  go_router: ^14.7.2
  google_fonts: ^6.2.1
  collection: ^1.18.0
  http_parser: ^4.0.2
  google_mobile_ads: ^6.0.0
  lottie: ^3.3.1

  material_color_utilities: ^0.11.0
  string_scanner: ^1.2.0
  google_maps_flutter: ^2.10.0
  intl: ^0.20.2
  mqtt_client: ^10.5.1
  http: ^1.3.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.6.2
  percent_indicator: ^4.2.4
  change_app_package_name: ^1.4.0
  firestore_cache: ^2.15.4
  printing: ^5.10.4
  provider: ^6.1.2
  firebase_auth: ^5.4.2
  image_picker: ^1.1.2
  timezone: ^0.10.0
  geocoding: ^3.0.0
  js: ^0.7.1
  flutter_svg: ^2.0.17
  shared_preferences: ^2.0.18
  dio: ^4.0.0
  flutter_polyline_points: ^2.1.0
  flutter_webview_plugin: ^0.4.0
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.15
  url_launcher_ios: ^ 6.3.2
  url_launcher_linux: ^ 3.2.1
  url_launcher_macos: ^ 3.2.2
  url_launcher_platform_interface: ^ 2.3.2
  url_launcher_web: ^ 2.4.0
  url_launcher_windows: ^ 3.1.4
  firebase_storage: ^12.4.4
  flutter_slidable: ^4.0.0
  pdf: any
  dotted_border: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  test_api: ^0.7.2
  flutter_launcher_icons: ^0.14.3
  image_gallery_saver: ^2.0.3
  file_picker: ^9.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/illustration/
    - assets/logo/
    - assets/audios/beep.mp3
    - assets/audios/caution.mp3
    - assets/audios/success.mp3
    - assets/audios/warning.mp3



flutter_launcher_icons:
  image_path: "assets/logo/Logo.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/logo/Logo.png"


#flutter pub run flutter_launcher_icons:main
